apiVersion: v1
kind: Service
metadata:
  name: barman-service
  namespace: default  # Adjust if you're using a different namespace
spec:
  selector:
    app: barman  # Ensure this matches the labels on your Barman pod
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP  # This creates a stable internal IP accessible within the cluster
