apiVersion: apps/v1
kind: Deployment
metadata:
  name: barman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barman
  template:
    metadata:
      labels:
        app: barman
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: barman
        image: barman:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /var/lib/barman
          name: barman-storage
        - mountPath: /etc/barman.conf
          subPath: barman.conf
          name: barman-config
      volumes:
      - name: barman-storage
        emptyDir: {}
      - name: barman-config
        configMap:
          name: barman-config
