apiVersion: v1
data:
  barman.conf: |
    [postgresql-server]
    description = "Main PostgreSQL server"
    conninfo = host=10.103.70.46 port=5432 user=barman dbname=postgres
    backup_method = rsync
    retention_policy = REDUNDANCY 2
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: barman-config
